# Generated by Django 5.2.6 on 2025-09-16 11:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_bytes', models.BigIntegerField(default=10737418240)),
                ('monthly_bytes', models.BigIntegerField(default=107374182400)),
                ('used_daily', models.BigIntegerField(default=0)),
                ('used_monthly', models.BigIntegerField(default=0)),
                ('last_reset', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=512)),
                ('total_size', models.BigIntegerField(blank=True, null=True)),
                ('total_chunks', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('assembling', 'Assembling'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploading', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('assembled_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=1024)),
                ('received', models.BooleanField(default=True)),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='file.uploadsession')),
            ],
            options={
                'unique_together': {('upload_session', 'chunk_index')},
            },
        ),
    ]
